name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 9,7,2 * * *,*" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "abhigowda0190@gmail.com"
          git config --local user.name "Abhishek-BG"
          git add -A
          
          arr[0]="Update "
          arr[1]="New Release"
          arr[2]="Fixing Vul"
          arr[3]="Adding new Features"
          arr[4]="Removing Features"
          arr[5]="Updated Index.js"
          arr[6]="Update Workflow"
          arr[7]="Fixing bugs"
          arr[8]="new commit"
          arr[9]="commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
